//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36279
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AED&quot;: &quot;United Arab Emirates Dirham&quot;,
        ///  &quot;AFN&quot;: &quot;Afghan Afghani&quot;,
        ///  &quot;ALL&quot;: &quot;Albanian Lek&quot;,
        ///  &quot;AMD&quot;: &quot;Armenian Dram&quot;,
        ///  &quot;ANG&quot;: &quot;Netherlands Antillean Guilder&quot;,
        ///  &quot;AOA&quot;: &quot;Angolan Kwanza&quot;,
        ///  &quot;ARS&quot;: &quot;Argentine Peso&quot;,
        ///  &quot;AUD&quot;: &quot;Australian Dollar&quot;,
        ///  &quot;AWG&quot;: &quot;Aruban Florin&quot;,
        ///  &quot;AZN&quot;: &quot;Azerbaijani Manat&quot;,
        ///  &quot;BAM&quot;: &quot;Bosnia-Herzegovina Convertible Mark&quot;,
        ///  &quot;BBD&quot;: &quot;Barbadian Dollar&quot;,
        ///  &quot;BDT&quot;: &quot;Bangladeshi Taka&quot;,
        ///  &quot;BGN&quot;: &quot;Bulgarian Lev&quot;,
        ///  &quot;BHD&quot;: &quot;Bahraini Dinar&quot;,
        ///  &quot;BIF&quot;: &quot;Burundian Franc&quot;,
        ///  &quot;BMD&quot;: &quot;Bermudan Doll [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string currencies {
            get {
                return ResourceManager.GetString("currencies", resourceCulture);
            }
        }
    }
}
