//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.1 C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g 2016-12-06 15:13:12

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;

namespace  Generated 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.1")]
[System.CLSCompliant(false)]
public partial class calcLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__9=9;
	public const int T__10=10;
	public const int T__11=11;
	public const int T__12=12;
	public const int T__13=13;
	public const int T__14=14;
	public const int T__15=15;
	public const int T__16=16;
	public const int T__17=17;
	public const int EXPONENT=4;
	public const int FLOAT=5;
	public const int ID=6;
	public const int NEWLINE=7;
	public const int SEPARATOR=8;

    // delegates
    // delegators

	public calcLexer()
	{
		OnCreated();
	}

	public calcLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public calcLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g"; } }

	private static readonly bool[] decisionCanBacktrack = new bool[0];

	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__9() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__9() {}

    // $ANTLR start "T__9"
    [GrammarRule("T__9")]
    private void mT__9()
    {
    	EnterRule_T__9();
    	EnterRule("T__9", 1);
    	TraceIn("T__9", 1);
    		try
    		{
    		int _type = T__9;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:9:6: ( '(' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:9:8: '('
    		{
    		DebugLocation(9, 8);
    		Match('('); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__9", 1);
    		LeaveRule("T__9", 1);
    		LeaveRule_T__9();
        }
    }
    // $ANTLR end "T__9"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__10() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__10() {}

    // $ANTLR start "T__10"
    [GrammarRule("T__10")]
    private void mT__10()
    {
    	EnterRule_T__10();
    	EnterRule("T__10", 2);
    	TraceIn("T__10", 2);
    		try
    		{
    		int _type = T__10;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:10:7: ( ')' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:10:9: ')'
    		{
    		DebugLocation(10, 9);
    		Match(')'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__10", 2);
    		LeaveRule("T__10", 2);
    		LeaveRule_T__10();
        }
    }
    // $ANTLR end "T__10"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__11() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__11() {}

    // $ANTLR start "T__11"
    [GrammarRule("T__11")]
    private void mT__11()
    {
    	EnterRule_T__11();
    	EnterRule("T__11", 3);
    	TraceIn("T__11", 3);
    		try
    		{
    		int _type = T__11;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:11:7: ( '*' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:11:9: '*'
    		{
    		DebugLocation(11, 9);
    		Match('*'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__11", 3);
    		LeaveRule("T__11", 3);
    		LeaveRule_T__11();
        }
    }
    // $ANTLR end "T__11"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__12() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__12() {}

    // $ANTLR start "T__12"
    [GrammarRule("T__12")]
    private void mT__12()
    {
    	EnterRule_T__12();
    	EnterRule("T__12", 4);
    	TraceIn("T__12", 4);
    		try
    		{
    		int _type = T__12;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:12:7: ( '+' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:12:9: '+'
    		{
    		DebugLocation(12, 9);
    		Match('+'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__12", 4);
    		LeaveRule("T__12", 4);
    		LeaveRule_T__12();
        }
    }
    // $ANTLR end "T__12"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__13() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__13() {}

    // $ANTLR start "T__13"
    [GrammarRule("T__13")]
    private void mT__13()
    {
    	EnterRule_T__13();
    	EnterRule("T__13", 5);
    	TraceIn("T__13", 5);
    		try
    		{
    		int _type = T__13;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:13:7: ( '-' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:13:9: '-'
    		{
    		DebugLocation(13, 9);
    		Match('-'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__13", 5);
    		LeaveRule("T__13", 5);
    		LeaveRule_T__13();
        }
    }
    // $ANTLR end "T__13"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__14() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__14() {}

    // $ANTLR start "T__14"
    [GrammarRule("T__14")]
    private void mT__14()
    {
    	EnterRule_T__14();
    	EnterRule("T__14", 6);
    	TraceIn("T__14", 6);
    		try
    		{
    		int _type = T__14;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:14:7: ( '/' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:14:9: '/'
    		{
    		DebugLocation(14, 9);
    		Match('/'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__14", 6);
    		LeaveRule("T__14", 6);
    		LeaveRule_T__14();
        }
    }
    // $ANTLR end "T__14"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__15() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__15() {}

    // $ANTLR start "T__15"
    [GrammarRule("T__15")]
    private void mT__15()
    {
    	EnterRule_T__15();
    	EnterRule("T__15", 7);
    	TraceIn("T__15", 7);
    		try
    		{
    		int _type = T__15;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:15:7: ( '=' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:15:9: '='
    		{
    		DebugLocation(15, 9);
    		Match('='); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__15", 7);
    		LeaveRule("T__15", 7);
    		LeaveRule_T__15();
        }
    }
    // $ANTLR end "T__15"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__16() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__16() {}

    // $ANTLR start "T__16"
    [GrammarRule("T__16")]
    private void mT__16()
    {
    	EnterRule_T__16();
    	EnterRule("T__16", 8);
    	TraceIn("T__16", 8);
    		try
    		{
    		int _type = T__16;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:16:7: ( '[' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:16:9: '['
    		{
    		DebugLocation(16, 9);
    		Match('['); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__16", 8);
    		LeaveRule("T__16", 8);
    		LeaveRule_T__16();
        }
    }
    // $ANTLR end "T__16"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__17() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__17() {}

    // $ANTLR start "T__17"
    [GrammarRule("T__17")]
    private void mT__17()
    {
    	EnterRule_T__17();
    	EnterRule("T__17", 9);
    	TraceIn("T__17", 9);
    		try
    		{
    		int _type = T__17;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:17:7: ( ']' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:17:9: ']'
    		{
    		DebugLocation(17, 9);
    		Match(']'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__17", 9);
    		LeaveRule("T__17", 9);
    		LeaveRule_T__17();
        }
    }
    // $ANTLR end "T__17"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_ID() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_ID() {}

    // $ANTLR start "ID"
    [GrammarRule("ID")]
    private void mID()
    {
    	EnterRule_ID();
    	EnterRule("ID", 10);
    	TraceIn("ID", 10);
    		try
    		{
    		int _type = ID;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:47:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:47:7: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    		{
    		DebugLocation(47, 7);
    		if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}

    		DebugLocation(47, 31);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:47:31: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    		try { DebugEnterSubRule(1);
    		while (true)
    		{
    			int alt1=2;
    			try { DebugEnterDecision(1, decisionCanBacktrack[1]);
    			int LA1_1 = input.LA(1);

    			if (((LA1_1>='0' && LA1_1<='9')||(LA1_1>='A' && LA1_1<='Z')||LA1_1=='_'||(LA1_1>='a' && LA1_1<='z')))
    			{
    				alt1 = 1;
    			}


    			} finally { DebugExitDecision(1); }
    			switch ( alt1 )
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    				{
    				DebugLocation(47, 31);
    				input.Consume();


    				}
    				break;

    			default:
    				goto loop1;
    			}
    		}

    		loop1:
    			;

    		} finally { DebugExitSubRule(1); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("ID", 10);
    		LeaveRule("ID", 10);
    		LeaveRule_ID();
        }
    }
    // $ANTLR end "ID"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_FLOAT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_FLOAT() {}

    // $ANTLR start "FLOAT"
    [GrammarRule("FLOAT")]
    private void mFLOAT()
    {
    	EnterRule_FLOAT();
    	EnterRule("FLOAT", 11);
    	TraceIn("FLOAT", 11);
    		try
    		{
    		int _type = FLOAT;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:51:5: ( ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ SEPARATOR ( '0' .. '9' )* ( EXPONENT )? | SEPARATOR ( '0' .. '9' )+ ( EXPONENT )? )
    		int alt9=3;
    		try { DebugEnterDecision(9, decisionCanBacktrack[9]);
    		try
    		{
    			alt9 = dfa9.Predict(input);
    		}
    		catch (NoViableAltException nvae)
    		{
    			DebugRecognitionException(nvae);
    			throw;
    		}
    		} finally { DebugExitDecision(9); }
    		switch (alt9)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:51:7: ( '0' .. '9' )+ ( EXPONENT )?
    			{
    			DebugLocation(51, 7);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:51:7: ( '0' .. '9' )+
    			int cnt2=0;
    			try { DebugEnterSubRule(2);
    			while (true)
    			{
    				int alt2=2;
    				try { DebugEnterDecision(2, decisionCanBacktrack[2]);
    				int LA2_1 = input.LA(1);

    				if (((LA2_1>='0' && LA2_1<='9')))
    				{
    					alt2 = 1;
    				}


    				} finally { DebugExitDecision(2); }
    				switch (alt2)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    					{
    					DebugLocation(51, 7);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt2 >= 1)
    						goto loop2;

    					EarlyExitException eee2 = new EarlyExitException( 2, input );
    					DebugRecognitionException(eee2);
    					throw eee2;
    				}
    				cnt2++;
    			}
    			loop2:
    				;

    			} finally { DebugExitSubRule(2); }

    			DebugLocation(51, 19);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:51:19: ( EXPONENT )?
    			int alt3=2;
    			try { DebugEnterSubRule(3);
    			try { DebugEnterDecision(3, decisionCanBacktrack[3]);
    			int LA3_1 = input.LA(1);

    			if ((LA3_1=='e'))
    			{
    				alt3 = 1;
    			}
    			} finally { DebugExitDecision(3); }
    			switch (alt3)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:51:19: EXPONENT
    				{
    				DebugLocation(51, 19);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(3); }


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:52:9: ( '0' .. '9' )+ SEPARATOR ( '0' .. '9' )* ( EXPONENT )?
    			{
    			DebugLocation(52, 9);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:52:9: ( '0' .. '9' )+
    			int cnt4=0;
    			try { DebugEnterSubRule(4);
    			while (true)
    			{
    				int alt4=2;
    				try { DebugEnterDecision(4, decisionCanBacktrack[4]);
    				int LA4_1 = input.LA(1);

    				if (((LA4_1>='0' && LA4_1<='9')))
    				{
    					alt4 = 1;
    				}


    				} finally { DebugExitDecision(4); }
    				switch (alt4)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    					{
    					DebugLocation(52, 9);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt4 >= 1)
    						goto loop4;

    					EarlyExitException eee4 = new EarlyExitException( 4, input );
    					DebugRecognitionException(eee4);
    					throw eee4;
    				}
    				cnt4++;
    			}
    			loop4:
    				;

    			} finally { DebugExitSubRule(4); }

    			DebugLocation(52, 21);
    			mSEPARATOR(); 
    			DebugLocation(52, 31);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:52:31: ( '0' .. '9' )*
    			try { DebugEnterSubRule(5);
    			while (true)
    			{
    				int alt5=2;
    				try { DebugEnterDecision(5, decisionCanBacktrack[5]);
    				int LA5_1 = input.LA(1);

    				if (((LA5_1>='0' && LA5_1<='9')))
    				{
    					alt5 = 1;
    				}


    				} finally { DebugExitDecision(5); }
    				switch ( alt5 )
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    					{
    					DebugLocation(52, 31);
    					input.Consume();


    					}
    					break;

    				default:
    					goto loop5;
    				}
    			}

    			loop5:
    				;

    			} finally { DebugExitSubRule(5); }

    			DebugLocation(52, 43);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:52:43: ( EXPONENT )?
    			int alt6=2;
    			try { DebugEnterSubRule(6);
    			try { DebugEnterDecision(6, decisionCanBacktrack[6]);
    			int LA6_1 = input.LA(1);

    			if ((LA6_1=='e'))
    			{
    				alt6 = 1;
    			}
    			} finally { DebugExitDecision(6); }
    			switch (alt6)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:52:43: EXPONENT
    				{
    				DebugLocation(52, 43);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(6); }


    			}
    			break;
    		case 3:
    			DebugEnterAlt(3);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:53:9: SEPARATOR ( '0' .. '9' )+ ( EXPONENT )?
    			{
    			DebugLocation(53, 9);
    			mSEPARATOR(); 
    			DebugLocation(53, 19);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:53:19: ( '0' .. '9' )+
    			int cnt7=0;
    			try { DebugEnterSubRule(7);
    			while (true)
    			{
    				int alt7=2;
    				try { DebugEnterDecision(7, decisionCanBacktrack[7]);
    				int LA7_1 = input.LA(1);

    				if (((LA7_1>='0' && LA7_1<='9')))
    				{
    					alt7 = 1;
    				}


    				} finally { DebugExitDecision(7); }
    				switch (alt7)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    					{
    					DebugLocation(53, 19);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt7 >= 1)
    						goto loop7;

    					EarlyExitException eee7 = new EarlyExitException( 7, input );
    					DebugRecognitionException(eee7);
    					throw eee7;
    				}
    				cnt7++;
    			}
    			loop7:
    				;

    			} finally { DebugExitSubRule(7); }

    			DebugLocation(53, 31);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:53:31: ( EXPONENT )?
    			int alt8=2;
    			try { DebugEnterSubRule(8);
    			try { DebugEnterDecision(8, decisionCanBacktrack[8]);
    			int LA8_1 = input.LA(1);

    			if ((LA8_1=='e'))
    			{
    				alt8 = 1;
    			}
    			} finally { DebugExitDecision(8); }
    			switch (alt8)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:53:31: EXPONENT
    				{
    				DebugLocation(53, 31);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(8); }


    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("FLOAT", 11);
    		LeaveRule("FLOAT", 11);
    		LeaveRule_FLOAT();
        }
    }
    // $ANTLR end "FLOAT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SEPARATOR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SEPARATOR() {}

    // $ANTLR start "SEPARATOR"
    [GrammarRule("SEPARATOR")]
    private void mSEPARATOR()
    {
    	EnterRule_SEPARATOR();
    	EnterRule("SEPARATOR", 12);
    	TraceIn("SEPARATOR", 12);
    		try
    		{
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:58:11: ( ( '.' | ',' ) )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    		{
    		DebugLocation(58, 11);
    		if (input.LA(1)==','||input.LA(1)=='.')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("SEPARATOR", 12);
    		LeaveRule("SEPARATOR", 12);
    		LeaveRule_SEPARATOR();
        }
    }
    // $ANTLR end "SEPARATOR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_EXPONENT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_EXPONENT() {}

    // $ANTLR start "EXPONENT"
    [GrammarRule("EXPONENT")]
    private void mEXPONENT()
    {
    	EnterRule_EXPONENT();
    	EnterRule("EXPONENT", 13);
    	TraceIn("EXPONENT", 13);
    		try
    		{
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:60:9: ( 'e' ( '+' | '-' )? ( '0' .. '9' )+ )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:60:11: 'e' ( '+' | '-' )? ( '0' .. '9' )+
    		{
    		DebugLocation(60, 11);
    		Match('e'); 
    		DebugLocation(60, 15);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:60:15: ( '+' | '-' )?
    		int alt10=2;
    		try { DebugEnterSubRule(10);
    		try { DebugEnterDecision(10, decisionCanBacktrack[10]);
    		int LA10_1 = input.LA(1);

    		if ((LA10_1=='+'||LA10_1=='-'))
    		{
    			alt10 = 1;
    		}
    		} finally { DebugExitDecision(10); }
    		switch (alt10)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    			{
    			DebugLocation(60, 15);
    			input.Consume();


    			}
    			break;

    		}
    		} finally { DebugExitSubRule(10); }

    		DebugLocation(60, 26);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:60:26: ( '0' .. '9' )+
    		int cnt11=0;
    		try { DebugEnterSubRule(11);
    		while (true)
    		{
    			int alt11=2;
    			try { DebugEnterDecision(11, decisionCanBacktrack[11]);
    			int LA11_1 = input.LA(1);

    			if (((LA11_1>='0' && LA11_1<='9')))
    			{
    				alt11 = 1;
    			}


    			} finally { DebugExitDecision(11); }
    			switch (alt11)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:
    				{
    				DebugLocation(60, 26);
    				input.Consume();


    				}
    				break;

    			default:
    				if (cnt11 >= 1)
    					goto loop11;

    				EarlyExitException eee11 = new EarlyExitException( 11, input );
    				DebugRecognitionException(eee11);
    				throw eee11;
    			}
    			cnt11++;
    		}
    		loop11:
    			;

    		} finally { DebugExitSubRule(11); }


    		}

    	}
    	finally
    	{
    		TraceOut("EXPONENT", 13);
    		LeaveRule("EXPONENT", 13);
    		LeaveRule_EXPONENT();
        }
    }
    // $ANTLR end "EXPONENT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_NEWLINE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_NEWLINE() {}

    // $ANTLR start "NEWLINE"
    [GrammarRule("NEWLINE")]
    private void mNEWLINE()
    {
    	EnterRule_NEWLINE();
    	EnterRule("NEWLINE", 14);
    	TraceIn("NEWLINE", 14);
    		try
    		{
    		int _type = NEWLINE;
    		int _channel = DefaultTokenChannel;
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:61:9: ( ( '\\r' )? '\\n' )
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:61:11: ( '\\r' )? '\\n'
    		{
    		DebugLocation(61, 11);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:61:11: ( '\\r' )?
    		int alt12=2;
    		try { DebugEnterSubRule(12);
    		try { DebugEnterDecision(12, decisionCanBacktrack[12]);
    		int LA12_1 = input.LA(1);

    		if ((LA12_1=='\r'))
    		{
    			alt12 = 1;
    		}
    		} finally { DebugExitDecision(12); }
    		switch (alt12)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:61:11: '\\r'
    			{
    			DebugLocation(61, 11);
    			Match('\r'); 

    			}
    			break;

    		}
    		} finally { DebugExitSubRule(12); }

    		DebugLocation(61, 17);
    		Match('\n'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("NEWLINE", 14);
    		LeaveRule("NEWLINE", 14);
    		LeaveRule_NEWLINE();
        }
    }
    // $ANTLR end "NEWLINE"

    public override void mTokens()
    {
    	// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:8: ( T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | ID | FLOAT | NEWLINE )
    	int alt13=12;
    	try { DebugEnterDecision(13, decisionCanBacktrack[13]);
    	switch (input.LA(1))
    	{
    	case '(':
    		{
    		alt13 = 1;
    		}
    		break;
    	case ')':
    		{
    		alt13 = 2;
    		}
    		break;
    	case '*':
    		{
    		alt13 = 3;
    		}
    		break;
    	case '+':
    		{
    		alt13 = 4;
    		}
    		break;
    	case '-':
    		{
    		alt13 = 5;
    		}
    		break;
    	case '/':
    		{
    		alt13 = 6;
    		}
    		break;
    	case '=':
    		{
    		alt13 = 7;
    		}
    		break;
    	case '[':
    		{
    		alt13 = 8;
    		}
    		break;
    	case ']':
    		{
    		alt13 = 9;
    		}
    		break;
    	case 'A':
    	case 'B':
    	case 'C':
    	case 'D':
    	case 'E':
    	case 'F':
    	case 'G':
    	case 'H':
    	case 'I':
    	case 'J':
    	case 'K':
    	case 'L':
    	case 'M':
    	case 'N':
    	case 'O':
    	case 'P':
    	case 'Q':
    	case 'R':
    	case 'S':
    	case 'T':
    	case 'U':
    	case 'V':
    	case 'W':
    	case 'X':
    	case 'Y':
    	case 'Z':
    	case '_':
    	case 'a':
    	case 'b':
    	case 'c':
    	case 'd':
    	case 'e':
    	case 'f':
    	case 'g':
    	case 'h':
    	case 'i':
    	case 'j':
    	case 'k':
    	case 'l':
    	case 'm':
    	case 'n':
    	case 'o':
    	case 'p':
    	case 'q':
    	case 'r':
    	case 's':
    	case 't':
    	case 'u':
    	case 'v':
    	case 'w':
    	case 'x':
    	case 'y':
    	case 'z':
    		{
    		alt13 = 10;
    		}
    		break;
    	case ',':
    	case '.':
    	case '0':
    	case '1':
    	case '2':
    	case '3':
    	case '4':
    	case '5':
    	case '6':
    	case '7':
    	case '8':
    	case '9':
    		{
    		alt13 = 11;
    		}
    		break;
    	case '\n':
    	case '\r':
    		{
    		alt13 = 12;
    		}
    		break;
    	default:
    		{
    			NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
    			DebugRecognitionException(nvae);
    			throw nvae;
    		}
    	}

    	} finally { DebugExitDecision(13); }
    	switch (alt13)
    	{
    	case 1:
    		DebugEnterAlt(1);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:10: T__9
    		{
    		DebugLocation(1, 10);
    		mT__9(); 

    		}
    		break;
    	case 2:
    		DebugEnterAlt(2);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:15: T__10
    		{
    		DebugLocation(1, 15);
    		mT__10(); 

    		}
    		break;
    	case 3:
    		DebugEnterAlt(3);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:21: T__11
    		{
    		DebugLocation(1, 21);
    		mT__11(); 

    		}
    		break;
    	case 4:
    		DebugEnterAlt(4);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:27: T__12
    		{
    		DebugLocation(1, 27);
    		mT__12(); 

    		}
    		break;
    	case 5:
    		DebugEnterAlt(5);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:33: T__13
    		{
    		DebugLocation(1, 33);
    		mT__13(); 

    		}
    		break;
    	case 6:
    		DebugEnterAlt(6);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:39: T__14
    		{
    		DebugLocation(1, 39);
    		mT__14(); 

    		}
    		break;
    	case 7:
    		DebugEnterAlt(7);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:45: T__15
    		{
    		DebugLocation(1, 45);
    		mT__15(); 

    		}
    		break;
    	case 8:
    		DebugEnterAlt(8);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:51: T__16
    		{
    		DebugLocation(1, 51);
    		mT__16(); 

    		}
    		break;
    	case 9:
    		DebugEnterAlt(9);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:57: T__17
    		{
    		DebugLocation(1, 57);
    		mT__17(); 

    		}
    		break;
    	case 10:
    		DebugEnterAlt(10);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:63: ID
    		{
    		DebugLocation(1, 63);
    		mID(); 

    		}
    		break;
    	case 11:
    		DebugEnterAlt(11);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:66: FLOAT
    		{
    		DebugLocation(1, 66);
    		mFLOAT(); 

    		}
    		break;
    	case 12:
    		DebugEnterAlt(12);
    		// C:\\Users\\illus\\OneDrive\\Документы\\Visual Studio 2015\\Projects\\Calculator\\calc.g:1:72: NEWLINE
    		{
    		DebugLocation(1, 72);
    		mNEWLINE(); 

    		}
    		break;

    	}

    }


	#region DFA
	DFA9 dfa9;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa9 = new DFA9(this);
	}

	private class DFA9 : DFA
	{
		private const string DFA9_eotS =
			"\x1\xFFFF\x1\x3\x3\xFFFF";
		private const string DFA9_eofS =
			"\x5\xFFFF";
		private const string DFA9_minS =
			"\x2\x2C\x3\xFFFF";
		private const string DFA9_maxS =
			"\x2\x39\x3\xFFFF";
		private const string DFA9_acceptS =
			"\x2\xFFFF\x1\x3\x1\x1\x1\x2";
		private const string DFA9_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA9_transitionS =
			{
				"\x1\x2\x1\xFFFF\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x4\x1\xFFFF\x1\x4\x1\xFFFF\xA\x1",
				"",
				"",
				""
			};

		private static readonly short[] DFA9_eot = DFA.UnpackEncodedString(DFA9_eotS);
		private static readonly short[] DFA9_eof = DFA.UnpackEncodedString(DFA9_eofS);
		private static readonly char[] DFA9_min = DFA.UnpackEncodedStringToUnsignedChars(DFA9_minS);
		private static readonly char[] DFA9_max = DFA.UnpackEncodedStringToUnsignedChars(DFA9_maxS);
		private static readonly short[] DFA9_accept = DFA.UnpackEncodedString(DFA9_acceptS);
		private static readonly short[] DFA9_special = DFA.UnpackEncodedString(DFA9_specialS);
		private static readonly short[][] DFA9_transition;

		static DFA9()
		{
			int numStates = DFA9_transitionS.Length;
			DFA9_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA9_transition[i] = DFA.UnpackEncodedString(DFA9_transitionS[i]);
			}
		}

		public DFA9( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 9;
			this.eot = DFA9_eot;
			this.eof = DFA9_eof;
			this.min = DFA9_min;
			this.max = DFA9_max;
			this.accept = DFA9_accept;
			this.special = DFA9_special;
			this.transition = DFA9_transition;
		}

		public override string Description { get { return "50:1: FLOAT : ( ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ SEPARATOR ( '0' .. '9' )* ( EXPONENT )? | SEPARATOR ( '0' .. '9' )+ ( EXPONENT )? );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}

} // namespace  Generated 
