//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.1 D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g 2016-12-09 17:35:07

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;

namespace  Generated 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.1")]
[System.CLSCompliant(false)]
public partial class GrammarOfArithmeticLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__10=10;
	public const int T__11=11;
	public const int T__12=12;
	public const int T__13=13;
	public const int T__14=14;
	public const int T__15=15;
	public const int T__16=16;
	public const int T__17=17;
	public const int T__18=18;
	public const int T__19=19;
	public const int T__20=20;
	public const int T__21=21;
	public const int T__22=22;
	public const int T__23=23;
	public const int T__24=24;
	public const int T__25=25;
	public const int T__26=26;
	public const int T__27=27;
	public const int T__28=28;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int T__45=45;
	public const int T__46=46;
	public const int T__47=47;
	public const int T__48=48;
	public const int T__49=49;
	public const int T__50=50;
	public const int T__51=51;
	public const int T__52=52;
	public const int T__53=53;
	public const int T__54=54;
	public const int T__55=55;
	public const int T__56=56;
	public const int T__57=57;
	public const int T__58=58;
	public const int T__59=59;
	public const int T__60=60;
	public const int EXPONENT=4;
	public const int FLOAT=5;
	public const int FLOATSEPARATOR=6;
	public const int ID=7;
	public const int NEWLINE=8;
	public const int SEPARATOR=9;

    // delegates
    // delegators

	public GrammarOfArithmeticLexer()
	{
		OnCreated();
	}

	public GrammarOfArithmeticLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public GrammarOfArithmeticLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g"; } }

	private static readonly bool[] decisionCanBacktrack = new bool[0];

	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__10() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__10() {}

    // $ANTLR start "T__10"
    [GrammarRule("T__10")]
    private void mT__10()
    {
    	EnterRule_T__10();
    	EnterRule("T__10", 1);
    	TraceIn("T__10", 1);
    		try
    		{
    		int _type = T__10;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:9:7: ( '!!' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:9:9: '!!'
    		{
    		DebugLocation(9, 9);
    		Match("!!"); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__10", 1);
    		LeaveRule("T__10", 1);
    		LeaveRule_T__10();
        }
    }
    // $ANTLR end "T__10"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__11() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__11() {}

    // $ANTLR start "T__11"
    [GrammarRule("T__11")]
    private void mT__11()
    {
    	EnterRule_T__11();
    	EnterRule("T__11", 2);
    	TraceIn("T__11", 2);
    		try
    		{
    		int _type = T__11;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:10:7: ( '!' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:10:9: '!'
    		{
    		DebugLocation(10, 9);
    		Match('!'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__11", 2);
    		LeaveRule("T__11", 2);
    		LeaveRule_T__11();
        }
    }
    // $ANTLR end "T__11"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__12() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__12() {}

    // $ANTLR start "T__12"
    [GrammarRule("T__12")]
    private void mT__12()
    {
    	EnterRule_T__12();
    	EnterRule("T__12", 3);
    	TraceIn("T__12", 3);
    		try
    		{
    		int _type = T__12;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:11:7: ( '(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:11:9: '('
    		{
    		DebugLocation(11, 9);
    		Match('('); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__12", 3);
    		LeaveRule("T__12", 3);
    		LeaveRule_T__12();
        }
    }
    // $ANTLR end "T__12"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__13() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__13() {}

    // $ANTLR start "T__13"
    [GrammarRule("T__13")]
    private void mT__13()
    {
    	EnterRule_T__13();
    	EnterRule("T__13", 4);
    	TraceIn("T__13", 4);
    		try
    		{
    		int _type = T__13;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:12:7: ( ')' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:12:9: ')'
    		{
    		DebugLocation(12, 9);
    		Match(')'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__13", 4);
    		LeaveRule("T__13", 4);
    		LeaveRule_T__13();
        }
    }
    // $ANTLR end "T__13"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__14() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__14() {}

    // $ANTLR start "T__14"
    [GrammarRule("T__14")]
    private void mT__14()
    {
    	EnterRule_T__14();
    	EnterRule("T__14", 5);
    	TraceIn("T__14", 5);
    		try
    		{
    		int _type = T__14;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:13:7: ( '*' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:13:9: '*'
    		{
    		DebugLocation(13, 9);
    		Match('*'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__14", 5);
    		LeaveRule("T__14", 5);
    		LeaveRule_T__14();
        }
    }
    // $ANTLR end "T__14"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__15() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__15() {}

    // $ANTLR start "T__15"
    [GrammarRule("T__15")]
    private void mT__15()
    {
    	EnterRule_T__15();
    	EnterRule("T__15", 6);
    	TraceIn("T__15", 6);
    		try
    		{
    		int _type = T__15;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:14:7: ( '+' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:14:9: '+'
    		{
    		DebugLocation(14, 9);
    		Match('+'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__15", 6);
    		LeaveRule("T__15", 6);
    		LeaveRule_T__15();
        }
    }
    // $ANTLR end "T__15"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__16() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__16() {}

    // $ANTLR start "T__16"
    [GrammarRule("T__16")]
    private void mT__16()
    {
    	EnterRule_T__16();
    	EnterRule("T__16", 7);
    	TraceIn("T__16", 7);
    		try
    		{
    		int _type = T__16;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:15:7: ( '-' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:15:9: '-'
    		{
    		DebugLocation(15, 9);
    		Match('-'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__16", 7);
    		LeaveRule("T__16", 7);
    		LeaveRule_T__16();
        }
    }
    // $ANTLR end "T__16"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__17() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__17() {}

    // $ANTLR start "T__17"
    [GrammarRule("T__17")]
    private void mT__17()
    {
    	EnterRule_T__17();
    	EnterRule("T__17", 8);
    	TraceIn("T__17", 8);
    		try
    		{
    		int _type = T__17;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:16:7: ( '/' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:16:9: '/'
    		{
    		DebugLocation(16, 9);
    		Match('/'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__17", 8);
    		LeaveRule("T__17", 8);
    		LeaveRule_T__17();
        }
    }
    // $ANTLR end "T__17"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__18() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__18() {}

    // $ANTLR start "T__18"
    [GrammarRule("T__18")]
    private void mT__18()
    {
    	EnterRule_T__18();
    	EnterRule("T__18", 9);
    	TraceIn("T__18", 9);
    		try
    		{
    		int _type = T__18;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:17:7: ( ':' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:17:9: ':'
    		{
    		DebugLocation(17, 9);
    		Match(':'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__18", 9);
    		LeaveRule("T__18", 9);
    		LeaveRule_T__18();
        }
    }
    // $ANTLR end "T__18"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__19() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__19() {}

    // $ANTLR start "T__19"
    [GrammarRule("T__19")]
    private void mT__19()
    {
    	EnterRule_T__19();
    	EnterRule("T__19", 10);
    	TraceIn("T__19", 10);
    		try
    		{
    		int _type = T__19;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:18:7: ( '<' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:18:9: '<'
    		{
    		DebugLocation(18, 9);
    		Match('<'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__19", 10);
    		LeaveRule("T__19", 10);
    		LeaveRule_T__19();
        }
    }
    // $ANTLR end "T__19"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__20() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__20() {}

    // $ANTLR start "T__20"
    [GrammarRule("T__20")]
    private void mT__20()
    {
    	EnterRule_T__20();
    	EnterRule("T__20", 11);
    	TraceIn("T__20", 11);
    		try
    		{
    		int _type = T__20;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:19:7: ( '=' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:19:9: '='
    		{
    		DebugLocation(19, 9);
    		Match('='); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__20", 11);
    		LeaveRule("T__20", 11);
    		LeaveRule_T__20();
        }
    }
    // $ANTLR end "T__20"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__21() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__21() {}

    // $ANTLR start "T__21"
    [GrammarRule("T__21")]
    private void mT__21()
    {
    	EnterRule_T__21();
    	EnterRule("T__21", 12);
    	TraceIn("T__21", 12);
    		try
    		{
    		int _type = T__21;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:20:7: ( '>' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:20:9: '>'
    		{
    		DebugLocation(20, 9);
    		Match('>'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__21", 12);
    		LeaveRule("T__21", 12);
    		LeaveRule_T__21();
        }
    }
    // $ANTLR end "T__21"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__22() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__22() {}

    // $ANTLR start "T__22"
    [GrammarRule("T__22")]
    private void mT__22()
    {
    	EnterRule_T__22();
    	EnterRule("T__22", 13);
    	TraceIn("T__22", 13);
    		try
    		{
    		int _type = T__22;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:21:7: ( '[' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:21:9: '['
    		{
    		DebugLocation(21, 9);
    		Match('['); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__22", 13);
    		LeaveRule("T__22", 13);
    		LeaveRule_T__22();
        }
    }
    // $ANTLR end "T__22"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__23() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__23() {}

    // $ANTLR start "T__23"
    [GrammarRule("T__23")]
    private void mT__23()
    {
    	EnterRule_T__23();
    	EnterRule("T__23", 14);
    	TraceIn("T__23", 14);
    		try
    		{
    		int _type = T__23;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:22:7: ( ']' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:22:9: ']'
    		{
    		DebugLocation(22, 9);
    		Match(']'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__23", 14);
    		LeaveRule("T__23", 14);
    		LeaveRule_T__23();
        }
    }
    // $ANTLR end "T__23"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__24() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__24() {}

    // $ANTLR start "T__24"
    [GrammarRule("T__24")]
    private void mT__24()
    {
    	EnterRule_T__24();
    	EnterRule("T__24", 15);
    	TraceIn("T__24", 15);
    		try
    		{
    		int _type = T__24;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:23:7: ( '^' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:23:9: '^'
    		{
    		DebugLocation(23, 9);
    		Match('^'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__24", 15);
    		LeaveRule("T__24", 15);
    		LeaveRule_T__24();
        }
    }
    // $ANTLR end "T__24"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__25() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__25() {}

    // $ANTLR start "T__25"
    [GrammarRule("T__25")]
    private void mT__25()
    {
    	EnterRule_T__25();
    	EnterRule("T__25", 16);
    	TraceIn("T__25", 16);
    		try
    		{
    		int _type = T__25;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:24:7: ( 'abs(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:24:9: 'abs('
    		{
    		DebugLocation(24, 9);
    		Match("abs("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__25", 16);
    		LeaveRule("T__25", 16);
    		LeaveRule_T__25();
        }
    }
    // $ANTLR end "T__25"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__26() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__26() {}

    // $ANTLR start "T__26"
    [GrammarRule("T__26")]
    private void mT__26()
    {
    	EnterRule_T__26();
    	EnterRule("T__26", 17);
    	TraceIn("T__26", 17);
    		try
    		{
    		int _type = T__26;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:25:7: ( 'acos(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:25:9: 'acos('
    		{
    		DebugLocation(25, 9);
    		Match("acos("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__26", 17);
    		LeaveRule("T__26", 17);
    		LeaveRule_T__26();
        }
    }
    // $ANTLR end "T__26"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__27() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__27() {}

    // $ANTLR start "T__27"
    [GrammarRule("T__27")]
    private void mT__27()
    {
    	EnterRule_T__27();
    	EnterRule("T__27", 18);
    	TraceIn("T__27", 18);
    		try
    		{
    		int _type = T__27;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:26:7: ( 'actg(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:26:9: 'actg('
    		{
    		DebugLocation(26, 9);
    		Match("actg("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__27", 18);
    		LeaveRule("T__27", 18);
    		LeaveRule_T__27();
        }
    }
    // $ANTLR end "T__27"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__28() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__28() {}

    // $ANTLR start "T__28"
    [GrammarRule("T__28")]
    private void mT__28()
    {
    	EnterRule_T__28();
    	EnterRule("T__28", 19);
    	TraceIn("T__28", 19);
    		try
    		{
    		int _type = T__28;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:27:7: ( 'asin(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:27:9: 'asin('
    		{
    		DebugLocation(27, 9);
    		Match("asin("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__28", 19);
    		LeaveRule("T__28", 19);
    		LeaveRule_T__28();
        }
    }
    // $ANTLR end "T__28"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__29() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__29() {}

    // $ANTLR start "T__29"
    [GrammarRule("T__29")]
    private void mT__29()
    {
    	EnterRule_T__29();
    	EnterRule("T__29", 20);
    	TraceIn("T__29", 20);
    		try
    		{
    		int _type = T__29;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:28:7: ( 'atg(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:28:9: 'atg('
    		{
    		DebugLocation(28, 9);
    		Match("atg("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__29", 20);
    		LeaveRule("T__29", 20);
    		LeaveRule_T__29();
        }
    }
    // $ANTLR end "T__29"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__30() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__30() {}

    // $ANTLR start "T__30"
    [GrammarRule("T__30")]
    private void mT__30()
    {
    	EnterRule_T__30();
    	EnterRule("T__30", 21);
    	TraceIn("T__30", 21);
    		try
    		{
    		int _type = T__30;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:29:7: ( 'atg2(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:29:9: 'atg2('
    		{
    		DebugLocation(29, 9);
    		Match("atg2("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__30", 21);
    		LeaveRule("T__30", 21);
    		LeaveRule_T__30();
        }
    }
    // $ANTLR end "T__30"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__31() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__31() {}

    // $ANTLR start "T__31"
    [GrammarRule("T__31")]
    private void mT__31()
    {
    	EnterRule_T__31();
    	EnterRule("T__31", 22);
    	TraceIn("T__31", 22);
    		try
    		{
    		int _type = T__31;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:30:7: ( 'ch(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:30:9: 'ch('
    		{
    		DebugLocation(30, 9);
    		Match("ch("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__31", 22);
    		LeaveRule("T__31", 22);
    		LeaveRule_T__31();
        }
    }
    // $ANTLR end "T__31"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__32() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__32() {}

    // $ANTLR start "T__32"
    [GrammarRule("T__32")]
    private void mT__32()
    {
    	EnterRule_T__32();
    	EnterRule("T__32", 23);
    	TraceIn("T__32", 23);
    		try
    		{
    		int _type = T__32;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:31:7: ( 'cos(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:31:9: 'cos('
    		{
    		DebugLocation(31, 9);
    		Match("cos("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__32", 23);
    		LeaveRule("T__32", 23);
    		LeaveRule_T__32();
        }
    }
    // $ANTLR end "T__32"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__33() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__33() {}

    // $ANTLR start "T__33"
    [GrammarRule("T__33")]
    private void mT__33()
    {
    	EnterRule_T__33();
    	EnterRule("T__33", 24);
    	TraceIn("T__33", 24);
    		try
    		{
    		int _type = T__33;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:32:7: ( 'cosec(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:32:9: 'cosec('
    		{
    		DebugLocation(32, 9);
    		Match("cosec("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__33", 24);
    		LeaveRule("T__33", 24);
    		LeaveRule_T__33();
        }
    }
    // $ANTLR end "T__33"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__34() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__34() {}

    // $ANTLR start "T__34"
    [GrammarRule("T__34")]
    private void mT__34()
    {
    	EnterRule_T__34();
    	EnterRule("T__34", 25);
    	TraceIn("T__34", 25);
    		try
    		{
    		int _type = T__34;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:33:7: ( 'csch(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:33:9: 'csch('
    		{
    		DebugLocation(33, 9);
    		Match("csch("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__34", 25);
    		LeaveRule("T__34", 25);
    		LeaveRule_T__34();
        }
    }
    // $ANTLR end "T__34"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__35() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__35() {}

    // $ANTLR start "T__35"
    [GrammarRule("T__35")]
    private void mT__35()
    {
    	EnterRule_T__35();
    	EnterRule("T__35", 26);
    	TraceIn("T__35", 26);
    		try
    		{
    		int _type = T__35;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:34:7: ( 'ctg(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:34:9: 'ctg('
    		{
    		DebugLocation(34, 9);
    		Match("ctg("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__35", 26);
    		LeaveRule("T__35", 26);
    		LeaveRule_T__35();
        }
    }
    // $ANTLR end "T__35"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__36() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__36() {}

    // $ANTLR start "T__36"
    [GrammarRule("T__36")]
    private void mT__36()
    {
    	EnterRule_T__36();
    	EnterRule("T__36", 27);
    	TraceIn("T__36", 27);
    		try
    		{
    		int _type = T__36;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:35:7: ( 'cth(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:35:9: 'cth('
    		{
    		DebugLocation(35, 9);
    		Match("cth("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__36", 27);
    		LeaveRule("T__36", 27);
    		LeaveRule_T__36();
        }
    }
    // $ANTLR end "T__36"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__37() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__37() {}

    // $ANTLR start "T__37"
    [GrammarRule("T__37")]
    private void mT__37()
    {
    	EnterRule_T__37();
    	EnterRule("T__37", 28);
    	TraceIn("T__37", 28);
    		try
    		{
    		int _type = T__37;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:36:7: ( 'div' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:36:9: 'div'
    		{
    		DebugLocation(36, 9);
    		Match("div"); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__37", 28);
    		LeaveRule("T__37", 28);
    		LeaveRule_T__37();
        }
    }
    // $ANTLR end "T__37"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__38() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__38() {}

    // $ANTLR start "T__38"
    [GrammarRule("T__38")]
    private void mT__38()
    {
    	EnterRule_T__38();
    	EnterRule("T__38", 29);
    	TraceIn("T__38", 29);
    		try
    		{
    		int _type = T__38;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:37:7: ( 'div(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:37:9: 'div('
    		{
    		DebugLocation(37, 9);
    		Match("div("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__38", 29);
    		LeaveRule("T__38", 29);
    		LeaveRule_T__38();
        }
    }
    // $ANTLR end "T__38"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__39() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__39() {}

    // $ANTLR start "T__39"
    [GrammarRule("T__39")]
    private void mT__39()
    {
    	EnterRule_T__39();
    	EnterRule("T__39", 30);
    	TraceIn("T__39", 30);
    		try
    		{
    		int _type = T__39;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:38:7: ( 'e' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:38:9: 'e'
    		{
    		DebugLocation(38, 9);
    		Match('e'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__39", 30);
    		LeaveRule("T__39", 30);
    		LeaveRule_T__39();
        }
    }
    // $ANTLR end "T__39"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__40() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__40() {}

    // $ANTLR start "T__40"
    [GrammarRule("T__40")]
    private void mT__40()
    {
    	EnterRule_T__40();
    	EnterRule("T__40", 31);
    	TraceIn("T__40", 31);
    		try
    		{
    		int _type = T__40;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:39:7: ( 'exp(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:39:9: 'exp('
    		{
    		DebugLocation(39, 9);
    		Match("exp("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__40", 31);
    		LeaveRule("T__40", 31);
    		LeaveRule_T__40();
        }
    }
    // $ANTLR end "T__40"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__41() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__41() {}

    // $ANTLR start "T__41"
    [GrammarRule("T__41")]
    private void mT__41()
    {
    	EnterRule_T__41();
    	EnterRule("T__41", 32);
    	TraceIn("T__41", 32);
    		try
    		{
    		int _type = T__41;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:40:7: ( 'lg(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:40:9: 'lg('
    		{
    		DebugLocation(40, 9);
    		Match("lg("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__41", 32);
    		LeaveRule("T__41", 32);
    		LeaveRule_T__41();
        }
    }
    // $ANTLR end "T__41"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__42() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__42() {}

    // $ANTLR start "T__42"
    [GrammarRule("T__42")]
    private void mT__42()
    {
    	EnterRule_T__42();
    	EnterRule("T__42", 33);
    	TraceIn("T__42", 33);
    		try
    		{
    		int _type = T__42;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:41:7: ( 'ln(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:41:9: 'ln('
    		{
    		DebugLocation(41, 9);
    		Match("ln("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__42", 33);
    		LeaveRule("T__42", 33);
    		LeaveRule_T__42();
        }
    }
    // $ANTLR end "T__42"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__43() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__43() {}

    // $ANTLR start "T__43"
    [GrammarRule("T__43")]
    private void mT__43()
    {
    	EnterRule_T__43();
    	EnterRule("T__43", 34);
    	TraceIn("T__43", 34);
    		try
    		{
    		int _type = T__43;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:42:7: ( 'log(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:42:9: 'log('
    		{
    		DebugLocation(42, 9);
    		Match("log("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__43", 34);
    		LeaveRule("T__43", 34);
    		LeaveRule_T__43();
        }
    }
    // $ANTLR end "T__43"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__44() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__44() {}

    // $ANTLR start "T__44"
    [GrammarRule("T__44")]
    private void mT__44()
    {
    	EnterRule_T__44();
    	EnterRule("T__44", 35);
    	TraceIn("T__44", 35);
    		try
    		{
    		int _type = T__44;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:43:7: ( 'max(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:43:9: 'max('
    		{
    		DebugLocation(43, 9);
    		Match("max("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__44", 35);
    		LeaveRule("T__44", 35);
    		LeaveRule_T__44();
        }
    }
    // $ANTLR end "T__44"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__45() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__45() {}

    // $ANTLR start "T__45"
    [GrammarRule("T__45")]
    private void mT__45()
    {
    	EnterRule_T__45();
    	EnterRule("T__45", 36);
    	TraceIn("T__45", 36);
    		try
    		{
    		int _type = T__45;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:44:7: ( 'min(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:44:9: 'min('
    		{
    		DebugLocation(44, 9);
    		Match("min("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__45", 36);
    		LeaveRule("T__45", 36);
    		LeaveRule_T__45();
        }
    }
    // $ANTLR end "T__45"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__46() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__46() {}

    // $ANTLR start "T__46"
    [GrammarRule("T__46")]
    private void mT__46()
    {
    	EnterRule_T__46();
    	EnterRule("T__46", 37);
    	TraceIn("T__46", 37);
    		try
    		{
    		int _type = T__46;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:45:7: ( 'mod' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:45:9: 'mod'
    		{
    		DebugLocation(45, 9);
    		Match("mod"); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__46", 37);
    		LeaveRule("T__46", 37);
    		LeaveRule_T__46();
        }
    }
    // $ANTLR end "T__46"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__47() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__47() {}

    // $ANTLR start "T__47"
    [GrammarRule("T__47")]
    private void mT__47()
    {
    	EnterRule_T__47();
    	EnterRule("T__47", 38);
    	TraceIn("T__47", 38);
    		try
    		{
    		int _type = T__47;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:46:7: ( 'mod(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:46:9: 'mod('
    		{
    		DebugLocation(46, 9);
    		Match("mod("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__47", 38);
    		LeaveRule("T__47", 38);
    		LeaveRule_T__47();
        }
    }
    // $ANTLR end "T__47"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__48() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__48() {}

    // $ANTLR start "T__48"
    [GrammarRule("T__48")]
    private void mT__48()
    {
    	EnterRule_T__48();
    	EnterRule("T__48", 39);
    	TraceIn("T__48", 39);
    		try
    		{
    		int _type = T__48;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:47:7: ( 'pi' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:47:9: 'pi'
    		{
    		DebugLocation(47, 9);
    		Match("pi"); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__48", 39);
    		LeaveRule("T__48", 39);
    		LeaveRule_T__48();
        }
    }
    // $ANTLR end "T__48"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__49() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__49() {}

    // $ANTLR start "T__49"
    [GrammarRule("T__49")]
    private void mT__49()
    {
    	EnterRule_T__49();
    	EnterRule("T__49", 40);
    	TraceIn("T__49", 40);
    		try
    		{
    		int _type = T__49;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:48:7: ( 'pow(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:48:9: 'pow('
    		{
    		DebugLocation(48, 9);
    		Match("pow("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__49", 40);
    		LeaveRule("T__49", 40);
    		LeaveRule_T__49();
        }
    }
    // $ANTLR end "T__49"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__50() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__50() {}

    // $ANTLR start "T__50"
    [GrammarRule("T__50")]
    private void mT__50()
    {
    	EnterRule_T__50();
    	EnterRule("T__50", 41);
    	TraceIn("T__50", 41);
    		try
    		{
    		int _type = T__50;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:49:7: ( 'root(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:49:9: 'root('
    		{
    		DebugLocation(49, 9);
    		Match("root("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__50", 41);
    		LeaveRule("T__50", 41);
    		LeaveRule_T__50();
        }
    }
    // $ANTLR end "T__50"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__51() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__51() {}

    // $ANTLR start "T__51"
    [GrammarRule("T__51")]
    private void mT__51()
    {
    	EnterRule_T__51();
    	EnterRule("T__51", 42);
    	TraceIn("T__51", 42);
    		try
    		{
    		int _type = T__51;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:50:7: ( 'sec(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:50:9: 'sec('
    		{
    		DebugLocation(50, 9);
    		Match("sec("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__51", 42);
    		LeaveRule("T__51", 42);
    		LeaveRule_T__51();
        }
    }
    // $ANTLR end "T__51"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__52() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__52() {}

    // $ANTLR start "T__52"
    [GrammarRule("T__52")]
    private void mT__52()
    {
    	EnterRule_T__52();
    	EnterRule("T__52", 43);
    	TraceIn("T__52", 43);
    		try
    		{
    		int _type = T__52;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:51:7: ( 'sech(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:51:9: 'sech('
    		{
    		DebugLocation(51, 9);
    		Match("sech("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__52", 43);
    		LeaveRule("T__52", 43);
    		LeaveRule_T__52();
        }
    }
    // $ANTLR end "T__52"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__53() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__53() {}

    // $ANTLR start "T__53"
    [GrammarRule("T__53")]
    private void mT__53()
    {
    	EnterRule_T__53();
    	EnterRule("T__53", 44);
    	TraceIn("T__53", 44);
    		try
    		{
    		int _type = T__53;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:52:7: ( 'sh(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:52:9: 'sh('
    		{
    		DebugLocation(52, 9);
    		Match("sh("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__53", 44);
    		LeaveRule("T__53", 44);
    		LeaveRule_T__53();
        }
    }
    // $ANTLR end "T__53"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__54() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__54() {}

    // $ANTLR start "T__54"
    [GrammarRule("T__54")]
    private void mT__54()
    {
    	EnterRule_T__54();
    	EnterRule("T__54", 45);
    	TraceIn("T__54", 45);
    		try
    		{
    		int _type = T__54;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:53:7: ( 'sin(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:53:9: 'sin('
    		{
    		DebugLocation(53, 9);
    		Match("sin("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__54", 45);
    		LeaveRule("T__54", 45);
    		LeaveRule_T__54();
        }
    }
    // $ANTLR end "T__54"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__55() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__55() {}

    // $ANTLR start "T__55"
    [GrammarRule("T__55")]
    private void mT__55()
    {
    	EnterRule_T__55();
    	EnterRule("T__55", 46);
    	TraceIn("T__55", 46);
    		try
    		{
    		int _type = T__55;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:54:7: ( 'sqr(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:54:9: 'sqr('
    		{
    		DebugLocation(54, 9);
    		Match("sqr("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__55", 46);
    		LeaveRule("T__55", 46);
    		LeaveRule_T__55();
        }
    }
    // $ANTLR end "T__55"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__56() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__56() {}

    // $ANTLR start "T__56"
    [GrammarRule("T__56")]
    private void mT__56()
    {
    	EnterRule_T__56();
    	EnterRule("T__56", 47);
    	TraceIn("T__56", 47);
    		try
    		{
    		int _type = T__56;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:55:7: ( 'sqrt(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:55:9: 'sqrt('
    		{
    		DebugLocation(55, 9);
    		Match("sqrt("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__56", 47);
    		LeaveRule("T__56", 47);
    		LeaveRule_T__56();
        }
    }
    // $ANTLR end "T__56"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__57() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__57() {}

    // $ANTLR start "T__57"
    [GrammarRule("T__57")]
    private void mT__57()
    {
    	EnterRule_T__57();
    	EnterRule("T__57", 48);
    	TraceIn("T__57", 48);
    		try
    		{
    		int _type = T__57;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:56:7: ( 'tg(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:56:9: 'tg('
    		{
    		DebugLocation(56, 9);
    		Match("tg("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__57", 48);
    		LeaveRule("T__57", 48);
    		LeaveRule_T__57();
        }
    }
    // $ANTLR end "T__57"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__58() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__58() {}

    // $ANTLR start "T__58"
    [GrammarRule("T__58")]
    private void mT__58()
    {
    	EnterRule_T__58();
    	EnterRule("T__58", 49);
    	TraceIn("T__58", 49);
    		try
    		{
    		int _type = T__58;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:57:7: ( 'th(' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:57:9: 'th('
    		{
    		DebugLocation(57, 9);
    		Match("th("); 


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__58", 49);
    		LeaveRule("T__58", 49);
    		LeaveRule_T__58();
        }
    }
    // $ANTLR end "T__58"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__59() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__59() {}

    // $ANTLR start "T__59"
    [GrammarRule("T__59")]
    private void mT__59()
    {
    	EnterRule_T__59();
    	EnterRule("T__59", 50);
    	TraceIn("T__59", 50);
    		try
    		{
    		int _type = T__59;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:58:7: ( '{' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:58:9: '{'
    		{
    		DebugLocation(58, 9);
    		Match('{'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__59", 50);
    		LeaveRule("T__59", 50);
    		LeaveRule_T__59();
        }
    }
    // $ANTLR end "T__59"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_T__60() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_T__60() {}

    // $ANTLR start "T__60"
    [GrammarRule("T__60")]
    private void mT__60()
    {
    	EnterRule_T__60();
    	EnterRule("T__60", 51);
    	TraceIn("T__60", 51);
    		try
    		{
    		int _type = T__60;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:59:7: ( '}' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:59:9: '}'
    		{
    		DebugLocation(59, 9);
    		Match('}'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("T__60", 51);
    		LeaveRule("T__60", 51);
    		LeaveRule_T__60();
        }
    }
    // $ANTLR end "T__60"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_ID() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_ID() {}

    // $ANTLR start "ID"
    [GrammarRule("ID")]
    private void mID()
    {
    	EnterRule_ID();
    	EnterRule("ID", 52);
    	TraceIn("ID", 52);
    		try
    		{
    		int _type = ID;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:142:5: ( ( 'a' .. 'z' | 'à' .. 'ÿ' | '_' ) ( 'a' .. 'z' | 'à' .. 'ÿ' | '0' .. '9' | '_' )* )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:142:7: ( 'a' .. 'z' | 'à' .. 'ÿ' | '_' ) ( 'a' .. 'z' | 'à' .. 'ÿ' | '0' .. '9' | '_' )*
    		{
    		DebugLocation(142, 7);
    		if (input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z')||(input.LA(1)>='\u0430' && input.LA(1)<='\u044F'))
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}

    		DebugLocation(142, 31);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:142:31: ( 'a' .. 'z' | 'à' .. 'ÿ' | '0' .. '9' | '_' )*
    		try { DebugEnterSubRule(1);
    		while (true)
    		{
    			int alt1=2;
    			try { DebugEnterDecision(1, decisionCanBacktrack[1]);
    			int LA1_1 = input.LA(1);

    			if (((LA1_1>='0' && LA1_1<='9')||LA1_1=='_'||(LA1_1>='a' && LA1_1<='z')||(LA1_1>='\u0430' && LA1_1<='\u044F')))
    			{
    				alt1 = 1;
    			}


    			} finally { DebugExitDecision(1); }
    			switch ( alt1 )
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    				{
    				DebugLocation(142, 31);
    				input.Consume();


    				}
    				break;

    			default:
    				goto loop1;
    			}
    		}

    		loop1:
    			;

    		} finally { DebugExitSubRule(1); }


    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("ID", 52);
    		LeaveRule("ID", 52);
    		LeaveRule_ID();
        }
    }
    // $ANTLR end "ID"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_FLOAT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_FLOAT() {}

    // $ANTLR start "FLOAT"
    [GrammarRule("FLOAT")]
    private void mFLOAT()
    {
    	EnterRule_FLOAT();
    	EnterRule("FLOAT", 53);
    	TraceIn("FLOAT", 53);
    		try
    		{
    		int _type = FLOAT;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:145:5: ( ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ FLOATSEPARATOR ( '0' .. '9' )* ( EXPONENT )? | FLOATSEPARATOR ( '0' .. '9' )+ ( EXPONENT )? )
    		int alt9=3;
    		try { DebugEnterDecision(9, decisionCanBacktrack[9]);
    		try
    		{
    			alt9 = dfa9.Predict(input);
    		}
    		catch (NoViableAltException nvae)
    		{
    			DebugRecognitionException(nvae);
    			throw;
    		}
    		} finally { DebugExitDecision(9); }
    		switch (alt9)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:145:7: ( '0' .. '9' )+ ( EXPONENT )?
    			{
    			DebugLocation(145, 7);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:145:7: ( '0' .. '9' )+
    			int cnt2=0;
    			try { DebugEnterSubRule(2);
    			while (true)
    			{
    				int alt2=2;
    				try { DebugEnterDecision(2, decisionCanBacktrack[2]);
    				int LA2_1 = input.LA(1);

    				if (((LA2_1>='0' && LA2_1<='9')))
    				{
    					alt2 = 1;
    				}


    				} finally { DebugExitDecision(2); }
    				switch (alt2)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    					{
    					DebugLocation(145, 7);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt2 >= 1)
    						goto loop2;

    					EarlyExitException eee2 = new EarlyExitException( 2, input );
    					DebugRecognitionException(eee2);
    					throw eee2;
    				}
    				cnt2++;
    			}
    			loop2:
    				;

    			} finally { DebugExitSubRule(2); }

    			DebugLocation(145, 19);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:145:19: ( EXPONENT )?
    			int alt3=2;
    			try { DebugEnterSubRule(3);
    			try { DebugEnterDecision(3, decisionCanBacktrack[3]);
    			int LA3_1 = input.LA(1);

    			if ((LA3_1=='e'))
    			{
    				alt3 = 1;
    			}
    			} finally { DebugExitDecision(3); }
    			switch (alt3)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:145:19: EXPONENT
    				{
    				DebugLocation(145, 19);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(3); }


    			}
    			break;
    		case 2:
    			DebugEnterAlt(2);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:146:9: ( '0' .. '9' )+ FLOATSEPARATOR ( '0' .. '9' )* ( EXPONENT )?
    			{
    			DebugLocation(146, 9);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:146:9: ( '0' .. '9' )+
    			int cnt4=0;
    			try { DebugEnterSubRule(4);
    			while (true)
    			{
    				int alt4=2;
    				try { DebugEnterDecision(4, decisionCanBacktrack[4]);
    				int LA4_1 = input.LA(1);

    				if (((LA4_1>='0' && LA4_1<='9')))
    				{
    					alt4 = 1;
    				}


    				} finally { DebugExitDecision(4); }
    				switch (alt4)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    					{
    					DebugLocation(146, 9);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt4 >= 1)
    						goto loop4;

    					EarlyExitException eee4 = new EarlyExitException( 4, input );
    					DebugRecognitionException(eee4);
    					throw eee4;
    				}
    				cnt4++;
    			}
    			loop4:
    				;

    			} finally { DebugExitSubRule(4); }

    			DebugLocation(146, 21);
    			mFLOATSEPARATOR(); 
    			DebugLocation(146, 36);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:146:36: ( '0' .. '9' )*
    			try { DebugEnterSubRule(5);
    			while (true)
    			{
    				int alt5=2;
    				try { DebugEnterDecision(5, decisionCanBacktrack[5]);
    				int LA5_1 = input.LA(1);

    				if (((LA5_1>='0' && LA5_1<='9')))
    				{
    					alt5 = 1;
    				}


    				} finally { DebugExitDecision(5); }
    				switch ( alt5 )
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    					{
    					DebugLocation(146, 36);
    					input.Consume();


    					}
    					break;

    				default:
    					goto loop5;
    				}
    			}

    			loop5:
    				;

    			} finally { DebugExitSubRule(5); }

    			DebugLocation(146, 48);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:146:48: ( EXPONENT )?
    			int alt6=2;
    			try { DebugEnterSubRule(6);
    			try { DebugEnterDecision(6, decisionCanBacktrack[6]);
    			int LA6_1 = input.LA(1);

    			if ((LA6_1=='e'))
    			{
    				alt6 = 1;
    			}
    			} finally { DebugExitDecision(6); }
    			switch (alt6)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:146:48: EXPONENT
    				{
    				DebugLocation(146, 48);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(6); }


    			}
    			break;
    		case 3:
    			DebugEnterAlt(3);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:147:9: FLOATSEPARATOR ( '0' .. '9' )+ ( EXPONENT )?
    			{
    			DebugLocation(147, 9);
    			mFLOATSEPARATOR(); 
    			DebugLocation(147, 24);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:147:24: ( '0' .. '9' )+
    			int cnt7=0;
    			try { DebugEnterSubRule(7);
    			while (true)
    			{
    				int alt7=2;
    				try { DebugEnterDecision(7, decisionCanBacktrack[7]);
    				int LA7_1 = input.LA(1);

    				if (((LA7_1>='0' && LA7_1<='9')))
    				{
    					alt7 = 1;
    				}


    				} finally { DebugExitDecision(7); }
    				switch (alt7)
    				{
    				case 1:
    					DebugEnterAlt(1);
    					// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    					{
    					DebugLocation(147, 24);
    					input.Consume();


    					}
    					break;

    				default:
    					if (cnt7 >= 1)
    						goto loop7;

    					EarlyExitException eee7 = new EarlyExitException( 7, input );
    					DebugRecognitionException(eee7);
    					throw eee7;
    				}
    				cnt7++;
    			}
    			loop7:
    				;

    			} finally { DebugExitSubRule(7); }

    			DebugLocation(147, 36);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:147:36: ( EXPONENT )?
    			int alt8=2;
    			try { DebugEnterSubRule(8);
    			try { DebugEnterDecision(8, decisionCanBacktrack[8]);
    			int LA8_1 = input.LA(1);

    			if ((LA8_1=='e'))
    			{
    				alt8 = 1;
    			}
    			} finally { DebugExitDecision(8); }
    			switch (alt8)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:147:36: EXPONENT
    				{
    				DebugLocation(147, 36);
    				mEXPONENT(); 

    				}
    				break;

    			}
    			} finally { DebugExitSubRule(8); }


    			}
    			break;

    		}
    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("FLOAT", 53);
    		LeaveRule("FLOAT", 53);
    		LeaveRule_FLOAT();
        }
    }
    // $ANTLR end "FLOAT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_FLOATSEPARATOR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_FLOATSEPARATOR() {}

    // $ANTLR start "FLOATSEPARATOR"
    [GrammarRule("FLOATSEPARATOR")]
    private void mFLOATSEPARATOR()
    {
    	EnterRule_FLOATSEPARATOR();
    	EnterRule("FLOATSEPARATOR", 54);
    	TraceIn("FLOATSEPARATOR", 54);
    		try
    		{
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:152:16: ( '.' | ',' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    		{
    		DebugLocation(152, 16);
    		if (input.LA(1)==','||input.LA(1)=='.')
    		{
    			input.Consume();
    		}
    		else
    		{
    			MismatchedSetException mse = new MismatchedSetException(null,input);
    			DebugRecognitionException(mse);
    			Recover(mse);
    			throw mse;
    		}


    		}

    	}
    	finally
    	{
    		TraceOut("FLOATSEPARATOR", 54);
    		LeaveRule("FLOATSEPARATOR", 54);
    		LeaveRule_FLOATSEPARATOR();
        }
    }
    // $ANTLR end "FLOATSEPARATOR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_SEPARATOR() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_SEPARATOR() {}

    // $ANTLR start "SEPARATOR"
    [GrammarRule("SEPARATOR")]
    private void mSEPARATOR()
    {
    	EnterRule_SEPARATOR();
    	EnterRule("SEPARATOR", 55);
    	TraceIn("SEPARATOR", 55);
    		try
    		{
    		int _type = SEPARATOR;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:152:11: ( ';' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:152:12: ';'
    		{
    		DebugLocation(152, 12);
    		Match(';'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("SEPARATOR", 55);
    		LeaveRule("SEPARATOR", 55);
    		LeaveRule_SEPARATOR();
        }
    }
    // $ANTLR end "SEPARATOR"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_EXPONENT() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_EXPONENT() {}

    // $ANTLR start "EXPONENT"
    [GrammarRule("EXPONENT")]
    private void mEXPONENT()
    {
    	EnterRule_EXPONENT();
    	EnterRule("EXPONENT", 56);
    	TraceIn("EXPONENT", 56);
    		try
    		{
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:155:9: ( 'e' ( '+' | '-' )? ( '0' .. '9' )+ )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:155:11: 'e' ( '+' | '-' )? ( '0' .. '9' )+
    		{
    		DebugLocation(155, 11);
    		Match('e'); 
    		DebugLocation(155, 15);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:155:15: ( '+' | '-' )?
    		int alt10=2;
    		try { DebugEnterSubRule(10);
    		try { DebugEnterDecision(10, decisionCanBacktrack[10]);
    		int LA10_1 = input.LA(1);

    		if ((LA10_1=='+'||LA10_1=='-'))
    		{
    			alt10 = 1;
    		}
    		} finally { DebugExitDecision(10); }
    		switch (alt10)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    			{
    			DebugLocation(155, 15);
    			input.Consume();


    			}
    			break;

    		}
    		} finally { DebugExitSubRule(10); }

    		DebugLocation(155, 26);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:155:26: ( '0' .. '9' )+
    		int cnt11=0;
    		try { DebugEnterSubRule(11);
    		while (true)
    		{
    			int alt11=2;
    			try { DebugEnterDecision(11, decisionCanBacktrack[11]);
    			int LA11_1 = input.LA(1);

    			if (((LA11_1>='0' && LA11_1<='9')))
    			{
    				alt11 = 1;
    			}


    			} finally { DebugExitDecision(11); }
    			switch (alt11)
    			{
    			case 1:
    				DebugEnterAlt(1);
    				// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:
    				{
    				DebugLocation(155, 26);
    				input.Consume();


    				}
    				break;

    			default:
    				if (cnt11 >= 1)
    					goto loop11;

    				EarlyExitException eee11 = new EarlyExitException( 11, input );
    				DebugRecognitionException(eee11);
    				throw eee11;
    			}
    			cnt11++;
    		}
    		loop11:
    			;

    		} finally { DebugExitSubRule(11); }


    		}

    	}
    	finally
    	{
    		TraceOut("EXPONENT", 56);
    		LeaveRule("EXPONENT", 56);
    		LeaveRule_EXPONENT();
        }
    }
    // $ANTLR end "EXPONENT"

    [Conditional("ANTLR_TRACE")]
    protected virtual void EnterRule_NEWLINE() {}
    [Conditional("ANTLR_TRACE")]
    protected virtual void LeaveRule_NEWLINE() {}

    // $ANTLR start "NEWLINE"
    [GrammarRule("NEWLINE")]
    private void mNEWLINE()
    {
    	EnterRule_NEWLINE();
    	EnterRule("NEWLINE", 57);
    	TraceIn("NEWLINE", 57);
    		try
    		{
    		int _type = NEWLINE;
    		int _channel = DefaultTokenChannel;
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:156:9: ( ( '\\r' )? '\\n' )
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:156:11: ( '\\r' )? '\\n'
    		{
    		DebugLocation(156, 11);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:156:11: ( '\\r' )?
    		int alt12=2;
    		try { DebugEnterSubRule(12);
    		try { DebugEnterDecision(12, decisionCanBacktrack[12]);
    		int LA12_1 = input.LA(1);

    		if ((LA12_1=='\r'))
    		{
    			alt12 = 1;
    		}
    		} finally { DebugExitDecision(12); }
    		switch (alt12)
    		{
    		case 1:
    			DebugEnterAlt(1);
    			// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:156:11: '\\r'
    			{
    			DebugLocation(156, 11);
    			Match('\r'); 

    			}
    			break;

    		}
    		} finally { DebugExitSubRule(12); }

    		DebugLocation(156, 17);
    		Match('\n'); 

    		}

    		state.type = _type;
    		state.channel = _channel;
    	}
    	finally
    	{
    		TraceOut("NEWLINE", 57);
    		LeaveRule("NEWLINE", 57);
    		LeaveRule_NEWLINE();
        }
    }
    // $ANTLR end "NEWLINE"

    public override void mTokens()
    {
    	// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:8: ( T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | ID | FLOAT | SEPARATOR | NEWLINE )
    	int alt13=55;
    	try { DebugEnterDecision(13, decisionCanBacktrack[13]);
    	try
    	{
    		alt13 = dfa13.Predict(input);
    	}
    	catch (NoViableAltException nvae)
    	{
    		DebugRecognitionException(nvae);
    		throw;
    	}
    	} finally { DebugExitDecision(13); }
    	switch (alt13)
    	{
    	case 1:
    		DebugEnterAlt(1);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:10: T__10
    		{
    		DebugLocation(1, 10);
    		mT__10(); 

    		}
    		break;
    	case 2:
    		DebugEnterAlt(2);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:16: T__11
    		{
    		DebugLocation(1, 16);
    		mT__11(); 

    		}
    		break;
    	case 3:
    		DebugEnterAlt(3);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:22: T__12
    		{
    		DebugLocation(1, 22);
    		mT__12(); 

    		}
    		break;
    	case 4:
    		DebugEnterAlt(4);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:28: T__13
    		{
    		DebugLocation(1, 28);
    		mT__13(); 

    		}
    		break;
    	case 5:
    		DebugEnterAlt(5);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:34: T__14
    		{
    		DebugLocation(1, 34);
    		mT__14(); 

    		}
    		break;
    	case 6:
    		DebugEnterAlt(6);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:40: T__15
    		{
    		DebugLocation(1, 40);
    		mT__15(); 

    		}
    		break;
    	case 7:
    		DebugEnterAlt(7);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:46: T__16
    		{
    		DebugLocation(1, 46);
    		mT__16(); 

    		}
    		break;
    	case 8:
    		DebugEnterAlt(8);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:52: T__17
    		{
    		DebugLocation(1, 52);
    		mT__17(); 

    		}
    		break;
    	case 9:
    		DebugEnterAlt(9);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:58: T__18
    		{
    		DebugLocation(1, 58);
    		mT__18(); 

    		}
    		break;
    	case 10:
    		DebugEnterAlt(10);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:64: T__19
    		{
    		DebugLocation(1, 64);
    		mT__19(); 

    		}
    		break;
    	case 11:
    		DebugEnterAlt(11);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:70: T__20
    		{
    		DebugLocation(1, 70);
    		mT__20(); 

    		}
    		break;
    	case 12:
    		DebugEnterAlt(12);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:76: T__21
    		{
    		DebugLocation(1, 76);
    		mT__21(); 

    		}
    		break;
    	case 13:
    		DebugEnterAlt(13);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:82: T__22
    		{
    		DebugLocation(1, 82);
    		mT__22(); 

    		}
    		break;
    	case 14:
    		DebugEnterAlt(14);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:88: T__23
    		{
    		DebugLocation(1, 88);
    		mT__23(); 

    		}
    		break;
    	case 15:
    		DebugEnterAlt(15);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:94: T__24
    		{
    		DebugLocation(1, 94);
    		mT__24(); 

    		}
    		break;
    	case 16:
    		DebugEnterAlt(16);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:100: T__25
    		{
    		DebugLocation(1, 100);
    		mT__25(); 

    		}
    		break;
    	case 17:
    		DebugEnterAlt(17);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:106: T__26
    		{
    		DebugLocation(1, 106);
    		mT__26(); 

    		}
    		break;
    	case 18:
    		DebugEnterAlt(18);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:112: T__27
    		{
    		DebugLocation(1, 112);
    		mT__27(); 

    		}
    		break;
    	case 19:
    		DebugEnterAlt(19);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:118: T__28
    		{
    		DebugLocation(1, 118);
    		mT__28(); 

    		}
    		break;
    	case 20:
    		DebugEnterAlt(20);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:124: T__29
    		{
    		DebugLocation(1, 124);
    		mT__29(); 

    		}
    		break;
    	case 21:
    		DebugEnterAlt(21);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:130: T__30
    		{
    		DebugLocation(1, 130);
    		mT__30(); 

    		}
    		break;
    	case 22:
    		DebugEnterAlt(22);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:136: T__31
    		{
    		DebugLocation(1, 136);
    		mT__31(); 

    		}
    		break;
    	case 23:
    		DebugEnterAlt(23);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:142: T__32
    		{
    		DebugLocation(1, 142);
    		mT__32(); 

    		}
    		break;
    	case 24:
    		DebugEnterAlt(24);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:148: T__33
    		{
    		DebugLocation(1, 148);
    		mT__33(); 

    		}
    		break;
    	case 25:
    		DebugEnterAlt(25);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:154: T__34
    		{
    		DebugLocation(1, 154);
    		mT__34(); 

    		}
    		break;
    	case 26:
    		DebugEnterAlt(26);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:160: T__35
    		{
    		DebugLocation(1, 160);
    		mT__35(); 

    		}
    		break;
    	case 27:
    		DebugEnterAlt(27);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:166: T__36
    		{
    		DebugLocation(1, 166);
    		mT__36(); 

    		}
    		break;
    	case 28:
    		DebugEnterAlt(28);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:172: T__37
    		{
    		DebugLocation(1, 172);
    		mT__37(); 

    		}
    		break;
    	case 29:
    		DebugEnterAlt(29);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:178: T__38
    		{
    		DebugLocation(1, 178);
    		mT__38(); 

    		}
    		break;
    	case 30:
    		DebugEnterAlt(30);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:184: T__39
    		{
    		DebugLocation(1, 184);
    		mT__39(); 

    		}
    		break;
    	case 31:
    		DebugEnterAlt(31);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:190: T__40
    		{
    		DebugLocation(1, 190);
    		mT__40(); 

    		}
    		break;
    	case 32:
    		DebugEnterAlt(32);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:196: T__41
    		{
    		DebugLocation(1, 196);
    		mT__41(); 

    		}
    		break;
    	case 33:
    		DebugEnterAlt(33);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:202: T__42
    		{
    		DebugLocation(1, 202);
    		mT__42(); 

    		}
    		break;
    	case 34:
    		DebugEnterAlt(34);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:208: T__43
    		{
    		DebugLocation(1, 208);
    		mT__43(); 

    		}
    		break;
    	case 35:
    		DebugEnterAlt(35);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:214: T__44
    		{
    		DebugLocation(1, 214);
    		mT__44(); 

    		}
    		break;
    	case 36:
    		DebugEnterAlt(36);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:220: T__45
    		{
    		DebugLocation(1, 220);
    		mT__45(); 

    		}
    		break;
    	case 37:
    		DebugEnterAlt(37);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:226: T__46
    		{
    		DebugLocation(1, 226);
    		mT__46(); 

    		}
    		break;
    	case 38:
    		DebugEnterAlt(38);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:232: T__47
    		{
    		DebugLocation(1, 232);
    		mT__47(); 

    		}
    		break;
    	case 39:
    		DebugEnterAlt(39);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:238: T__48
    		{
    		DebugLocation(1, 238);
    		mT__48(); 

    		}
    		break;
    	case 40:
    		DebugEnterAlt(40);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:244: T__49
    		{
    		DebugLocation(1, 244);
    		mT__49(); 

    		}
    		break;
    	case 41:
    		DebugEnterAlt(41);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:250: T__50
    		{
    		DebugLocation(1, 250);
    		mT__50(); 

    		}
    		break;
    	case 42:
    		DebugEnterAlt(42);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:256: T__51
    		{
    		DebugLocation(1, 256);
    		mT__51(); 

    		}
    		break;
    	case 43:
    		DebugEnterAlt(43);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:262: T__52
    		{
    		DebugLocation(1, 262);
    		mT__52(); 

    		}
    		break;
    	case 44:
    		DebugEnterAlt(44);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:268: T__53
    		{
    		DebugLocation(1, 268);
    		mT__53(); 

    		}
    		break;
    	case 45:
    		DebugEnterAlt(45);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:274: T__54
    		{
    		DebugLocation(1, 274);
    		mT__54(); 

    		}
    		break;
    	case 46:
    		DebugEnterAlt(46);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:280: T__55
    		{
    		DebugLocation(1, 280);
    		mT__55(); 

    		}
    		break;
    	case 47:
    		DebugEnterAlt(47);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:286: T__56
    		{
    		DebugLocation(1, 286);
    		mT__56(); 

    		}
    		break;
    	case 48:
    		DebugEnterAlt(48);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:292: T__57
    		{
    		DebugLocation(1, 292);
    		mT__57(); 

    		}
    		break;
    	case 49:
    		DebugEnterAlt(49);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:298: T__58
    		{
    		DebugLocation(1, 298);
    		mT__58(); 

    		}
    		break;
    	case 50:
    		DebugEnterAlt(50);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:304: T__59
    		{
    		DebugLocation(1, 304);
    		mT__59(); 

    		}
    		break;
    	case 51:
    		DebugEnterAlt(51);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:310: T__60
    		{
    		DebugLocation(1, 310);
    		mT__60(); 

    		}
    		break;
    	case 52:
    		DebugEnterAlt(52);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:316: ID
    		{
    		DebugLocation(1, 316);
    		mID(); 

    		}
    		break;
    	case 53:
    		DebugEnterAlt(53);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:319: FLOAT
    		{
    		DebugLocation(1, 319);
    		mFLOAT(); 

    		}
    		break;
    	case 54:
    		DebugEnterAlt(54);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:325: SEPARATOR
    		{
    		DebugLocation(1, 325);
    		mSEPARATOR(); 

    		}
    		break;
    	case 55:
    		DebugEnterAlt(55);
    		// D:\\project\\C#\\Calculator\\GrammarOfArithmetic.g:1:335: NEWLINE
    		{
    		DebugLocation(1, 335);
    		mNEWLINE(); 

    		}
    		break;

    	}

    }


	#region DFA
	DFA9 dfa9;
	DFA13 dfa13;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa9 = new DFA9(this);
		dfa13 = new DFA13(this);
	}

	private class DFA9 : DFA
	{
		private const string DFA9_eotS =
			"\x1\xFFFF\x1\x3\x3\xFFFF";
		private const string DFA9_eofS =
			"\x5\xFFFF";
		private const string DFA9_minS =
			"\x2\x2C\x3\xFFFF";
		private const string DFA9_maxS =
			"\x2\x39\x3\xFFFF";
		private const string DFA9_acceptS =
			"\x2\xFFFF\x1\x3\x1\x1\x1\x2";
		private const string DFA9_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA9_transitionS =
			{
				"\x1\x2\x1\xFFFF\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x4\x1\xFFFF\x1\x4\x1\xFFFF\xA\x1",
				"",
				"",
				""
			};

		private static readonly short[] DFA9_eot = DFA.UnpackEncodedString(DFA9_eotS);
		private static readonly short[] DFA9_eof = DFA.UnpackEncodedString(DFA9_eofS);
		private static readonly char[] DFA9_min = DFA.UnpackEncodedStringToUnsignedChars(DFA9_minS);
		private static readonly char[] DFA9_max = DFA.UnpackEncodedStringToUnsignedChars(DFA9_maxS);
		private static readonly short[] DFA9_accept = DFA.UnpackEncodedString(DFA9_acceptS);
		private static readonly short[] DFA9_special = DFA.UnpackEncodedString(DFA9_specialS);
		private static readonly short[][] DFA9_transition;

		static DFA9()
		{
			int numStates = DFA9_transitionS.Length;
			DFA9_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA9_transition[i] = DFA.UnpackEncodedString(DFA9_transitionS[i]);
			}
		}

		public DFA9( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 9;
			this.eot = DFA9_eot;
			this.eof = DFA9_eof;
			this.min = DFA9_min;
			this.max = DFA9_max;
			this.accept = DFA9_accept;
			this.special = DFA9_special;
			this.transition = DFA9_transition;
		}

		public override string Description { get { return "144:1: FLOAT : ( ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ FLOATSEPARATOR ( '0' .. '9' )* ( EXPONENT )? | FLOATSEPARATOR ( '0' .. '9' )+ ( EXPONENT )? );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA13 : DFA
	{
		private const string DFA13_eotS =
			"\x1\xFFFF\x1\x20\xD\xFFFF\x3\x1B\x1\x2B\x6\x1B\x8\xFFFF\xA\x1B\x1\xFFFF"+
			"\x6\x1B\x1\x4D\xD\x1B\x1\xFFFF\x4\x1B\x1\x62\x1\x1B\x2\xFFFF\x3\x1B\x1"+
			"\x68\x1\xFFFF\x3\x1B\x1\xFFFF\x2\x1B\x3\xFFFF\x3\x1B\x1\xFFFF\x1\x1B"+
			"\x1\xFFFF\x2\x1B\xB\xFFFF\x1\x1B\x1\xFFFF\x1\x1B\x2\xFFFF\x1\x1B\x4\xFFFF"+
			"\x1\x1B\x5\xFFFF";
		private const string DFA13_eofS =
			"\x7A\xFFFF";
		private const string DFA13_minS =
			"\x1\xA\x1\x21\xD\xFFFF\x1\x62\x1\x68\x1\x69\x1\x30\x1\x67\x1\x61\x1\x69"+
			"\x1\x6F\x1\x65\x1\x67\x8\xFFFF\x1\x73\x1\x6F\x1\x69\x1\x67\x1\x28\x1"+
			"\x73\x1\x63\x1\x67\x1\x76\x1\x70\x1\xFFFF\x2\x28\x1\x67\x1\x78\x1\x6E"+
			"\x1\x64\x1\x30\x1\x77\x1\x6F\x1\x63\x1\x28\x1\x6E\x1\x72\x3\x28\x1\x73"+
			"\x1\x67\x1\x6E\x1\x28\x1\xFFFF\x1\x28\x1\x68\x4\x28\x2\xFFFF\x4\x28\x1"+
			"\xFFFF\x1\x28\x1\x74\x1\x28\x1\xFFFF\x2\x28\x3\xFFFF\x3\x28\x1\xFFFF"+
			"\x1\x28\x1\xFFFF\x1\x63\x1\x28\xB\xFFFF\x1\x28\x1\xFFFF\x1\x28\x2\xFFFF"+
			"\x1\x28\x4\xFFFF\x1\x28\x5\xFFFF";
		private const string DFA13_maxS =
			"\x1\x44F\x1\x21\xD\xFFFF\x2\x74\x1\x69\x1\x44F\x4\x6F\x1\x71\x1\x68\x8"+
			"\xFFFF\x1\x73\x1\x74\x1\x69\x1\x67\x1\x28\x1\x73\x1\x63\x1\x68\x1\x76"+
			"\x1\x70\x1\xFFFF\x2\x28\x1\x67\x1\x78\x1\x6E\x1\x64\x1\x44F\x1\x77\x1"+
			"\x6F\x1\x63\x1\x28\x1\x6E\x1\x72\x3\x28\x1\x73\x1\x67\x1\x6E\x1\x32\x1"+
			"\xFFFF\x1\x65\x1\x68\x2\x28\x1\x44F\x1\x28\x2\xFFFF\x3\x28\x1\x44F\x1"+
			"\xFFFF\x1\x28\x1\x74\x1\x68\x1\xFFFF\x1\x28\x1\x74\x3\xFFFF\x3\x28\x1"+
			"\xFFFF\x1\x28\x1\xFFFF\x1\x63\x1\x28\xB\xFFFF\x1\x28\x1\xFFFF\x1\x28"+
			"\x2\xFFFF\x1\x28\x4\xFFFF\x1\x28\x5\xFFFF";
		private const string DFA13_acceptS =
			"\x2\xFFFF\x1\x3\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x1\x9\x1\xA\x1\xB\x1\xC"+
			"\x1\xD\x1\xE\x1\xF\xA\xFFFF\x1\x32\x1\x33\x1\x34\x1\x35\x1\x36\x1\x37"+
			"\x1\x1\x1\x2\xA\xFFFF\x1\x1E\x14\xFFFF\x1\x16\x6\xFFFF\x1\x20\x1\x21"+
			"\x4\xFFFF\x1\x27\x3\xFFFF\x1\x2C\x2\xFFFF\x1\x30\x1\x31\x1\x10\x3\xFFFF"+
			"\x1\x14\x1\xFFFF\x1\x17\x2\xFFFF\x1\x1A\x1\x1B\x1\x1D\x1\x1C\x1\x1F\x1"+
			"\x22\x1\x23\x1\x24\x1\x26\x1\x25\x1\x28\x1\xFFFF\x1\x2A\x1\xFFFF\x1\x2D"+
			"\x1\x2E\x1\xFFFF\x1\x11\x1\x12\x1\x13\x1\x15\x1\xFFFF\x1\x19\x1\x29\x1"+
			"\x2B\x1\x2F\x1\x18";
		private const string DFA13_specialS =
			"\x7A\xFFFF}>";
		private static readonly string[] DFA13_transitionS =
			{
				"\x1\x1E\x2\xFFFF\x1\x1E\x13\xFFFF\x1\x1\x6\xFFFF\x1\x2\x1\x3\x1\x4\x1"+
				"\x5\x1\x1C\x1\x6\x1\x1C\x1\x7\xA\x1C\x1\x8\x1\x1D\x1\x9\x1\xA\x1\xB"+
				"\x1C\xFFFF\x1\xC\x1\xFFFF\x1\xD\x1\xE\x1\x1B\x1\xFFFF\x1\xF\x1\x1B\x1"+
				"\x10\x1\x11\x1\x12\x6\x1B\x1\x13\x1\x14\x2\x1B\x1\x15\x1\x1B\x1\x16"+
				"\x1\x17\x1\x18\x6\x1B\x1\x19\x1\xFFFF\x1\x1A\x3B2\xFFFF\x20\x1B",
				"\x1\x1F",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x21\x1\x22\xF\xFFFF\x1\x23\x1\x24",
				"\x1\x25\x6\xFFFF\x1\x26\x3\xFFFF\x1\x27\x1\x28",
				"\x1\x29",
				"\xA\x1B\x25\xFFFF\x1\x1B\x1\xFFFF\x17\x1B\x1\x2A\x2\x1B\x3B5\xFFFF"+
				"\x20\x1B",
				"\x1\x2C\x6\xFFFF\x1\x2D\x1\x2E",
				"\x1\x2F\x7\xFFFF\x1\x30\x5\xFFFF\x1\x31",
				"\x1\x32\x5\xFFFF\x1\x33",
				"\x1\x34",
				"\x1\x35\x2\xFFFF\x1\x36\x1\x37\x7\xFFFF\x1\x38",
				"\x1\x39\x1\x3A",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x3B",
				"\x1\x3C\x4\xFFFF\x1\x3D",
				"\x1\x3E",
				"\x1\x3F",
				"\x1\x40",
				"\x1\x41",
				"\x1\x42",
				"\x1\x43\x1\x44",
				"\x1\x45",
				"\x1\x46",
				"",
				"\x1\x47",
				"\x1\x48",
				"\x1\x49",
				"\x1\x4A",
				"\x1\x4B",
				"\x1\x4C",
				"\xA\x1B\x25\xFFFF\x1\x1B\x1\xFFFF\x1A\x1B\x3B5\xFFFF\x20\x1B",
				"\x1\x4E",
				"\x1\x4F",
				"\x1\x50",
				"\x1\x51",
				"\x1\x52",
				"\x1\x53",
				"\x1\x54",
				"\x1\x55",
				"\x1\x56",
				"\x1\x57",
				"\x1\x58",
				"\x1\x59",
				"\x1\x5A\x9\xFFFF\x1\x5B",
				"",
				"\x1\x5C\x3C\xFFFF\x1\x5D",
				"\x1\x5E",
				"\x1\x5F",
				"\x1\x60",
				"\x1\x61\x7\xFFFF\xA\x1B\x25\xFFFF\x1\x1B\x1\xFFFF\x1A\x1B\x3B5\xFFFF"+
				"\x20\x1B",
				"\x1\x63",
				"",
				"",
				"\x1\x64",
				"\x1\x65",
				"\x1\x66",
				"\x1\x67\x7\xFFFF\xA\x1B\x25\xFFFF\x1\x1B\x1\xFFFF\x1A\x1B\x3B5\xFFFF"+
				"\x20\x1B",
				"",
				"\x1\x69",
				"\x1\x6A",
				"\x1\x6B\x3F\xFFFF\x1\x6C",
				"",
				"\x1\x6D",
				"\x1\x6E\x4B\xFFFF\x1\x6F",
				"",
				"",
				"",
				"\x1\x70",
				"\x1\x71",
				"\x1\x72",
				"",
				"\x1\x73",
				"",
				"\x1\x74",
				"\x1\x75",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x76",
				"",
				"\x1\x77",
				"",
				"",
				"\x1\x78",
				"",
				"",
				"",
				"",
				"\x1\x79",
				"",
				"",
				"",
				"",
				""
			};

		private static readonly short[] DFA13_eot = DFA.UnpackEncodedString(DFA13_eotS);
		private static readonly short[] DFA13_eof = DFA.UnpackEncodedString(DFA13_eofS);
		private static readonly char[] DFA13_min = DFA.UnpackEncodedStringToUnsignedChars(DFA13_minS);
		private static readonly char[] DFA13_max = DFA.UnpackEncodedStringToUnsignedChars(DFA13_maxS);
		private static readonly short[] DFA13_accept = DFA.UnpackEncodedString(DFA13_acceptS);
		private static readonly short[] DFA13_special = DFA.UnpackEncodedString(DFA13_specialS);
		private static readonly short[][] DFA13_transition;

		static DFA13()
		{
			int numStates = DFA13_transitionS.Length;
			DFA13_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA13_transition[i] = DFA.UnpackEncodedString(DFA13_transitionS[i]);
			}
		}

		public DFA13( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 13;
			this.eot = DFA13_eot;
			this.eof = DFA13_eof;
			this.min = DFA13_min;
			this.max = DFA13_max;
			this.accept = DFA13_accept;
			this.special = DFA13_special;
			this.transition = DFA13_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | ID | FLOAT | SEPARATOR | NEWLINE );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}

} // namespace  Generated 
